[package]
name = "aoc-2021"
version = "0.1.0"
authors = ["Henrik Karlsson <hk.henrik@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

clap = "2.33.3"
regex = "1.4.2"
